### ISSUE TITLE
Create an FAQ

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/webpayments#114]
We should have an FAQ to help explain the core Payment Request API and other deliverables of the WG and what problems the group’s work is intended to solve.

Unless I am missing something, we don’t currently have such and FAQ or equivalent.

I am aware of https://www.w3.org/Payments/IG/wiki/Web_Payments_WG_Charter_FAQ but that’s not really current and as far as I can see, not meant to be continued to be maintained going forward.

What I think we need instead is a fresh FAQ that covers the current set of deliverables that the WG’s work has coalesced on. It would be great to have it done to accompany that FPWD publications but at this point it seems somewhat unrealistic to aim for that.

Note also that I am not volunteering to write up the FAQ myself. If we are to do it, I would rather we get some volunteers from the WG to put time into it, though I would be very glad to help and pitch in on it if we can in fact get others to commit to working on it.

**Comment by ianbjacobs** [comment]
@sideshowbarker,

I've started work on a FAQ to accompany FPWD and welcome feedback from the WG:
 https://github.com/w3c/webpayments/wiki/PaymentRequestFAQ

Ian

**Comment by sideshowbarker** [comment]
We now have https://github.com/w3c/webpayments/wiki/PaymentRequestFAQ thanks to @ianbjacobs so this is resolved.
