### ISSUE TITLE
PROPOSAL: A new document structure for this API

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webpayments#134]
Migrated from https://github.com/w3c/browser-payment-api/issues/138

There are a number of issues raised and comments made about the need to explicitly define the role of payment mediator and user agent. I propose that we separate the current API spec into a spec defining the conformance criteria for a payment mediator and a spec defining conformance criteria for a user agent in it's role as a payment mediator but also in its role as data collection service to optimize the checkout flow.
## Proposal
1. Create a new payment mediator specification that defines the conformance criteria for any mediator (not just a user agent in this role).
2. Migrate the appropriate elements of the API specification into this new specification.
3. Make the new specification a normative dependency of the API specification.
4. Update the API specification so that it describes the conformance criteria of a user agent in assuming two roles:
   1. Payment mediator (as defined in the payment mediator spec)
   2. Data collection mediator for collection of data to optimize the checkout flow.

**Comment by ianbjacobs** [comment]
I am of two minds:

1) Because the browser is going to be the primary mediator, I think ideally we'd add the "browser-as-mediator" role to the paymentRequest specification, and not deal with "abstract mediators" for now at least.

2) One can design a payment app layer on top of paymentRequest. If we are going to take this approach and not touch paymentRequest, then I am ok creating a separate spec for the mediator. However, even in this case I have a much stronger preference to start with the specific case of browser-as-mediator rather than abstract without experience.

Ian

**Comment by msporny** [comment]
@ianbjacobs wrote:

> Because the browser is going to be the primary mediator

This may be true in the first several years of deployment, but I'm skeptical that this will continue to stay true as the years roll on. For example, There are currently 4.9B IoT devices, with numbers projected to hit 20.7B in 4 years. I suspect that a number of those devices may become payment mediators.

> rather than abstract without experience

We already have semi-automated / automated payment use cases with the HTTP API, so I don't think that the discussion is abstract.

I haven't quite figured out if I agree with @adrianhopebailie's proposal, but one concrete way we'll know if we need something like it is if we start duplicating mediator conformance criteria in both specs (and I think we're already well down that path):

http://w3c.github.io/webpayments-http-api/#payment-flow-overview

**Comment by msporny** [comment]
@adrianhopebailie wrote:

> Proposal:
> Create a new payment mediator specification that defines the conformance criteria for any mediator (not just a user agent in this role).

+0.4 - it would help to know what the conformance criteria for a mediator would be - do you have a short list?

> Migrate the appropriate elements of the API specification into this new specification.

+0 - unsure about this bit if it means taking the WebIDL and placing it into a mediator spec that the HTTP API spec can't build on top of.

> Make the new specification a normative dependency of the API specification.

+1, the PaymentRequest API currently feels like it's conflating two concepts (which you go into below):

> Update the API specification so that it describes the conformance criteria of a user agent in assuming two roles:
> - Payment mediator (as defined in the payment mediator spec)
> - Data collection mediator for collection of data to optimize the checkout flow.

+0.8

**Comment by adrianhopebailie** [comment]
The group has adopted an overview document instead of an architecture document. This issue no longer seems relevant.
