### ISSUE TITLE
[Payment apps] Should payment instrument details be included at registration?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments#142]
Should the registration data also include details about payment instruments? This would allow the browser to display more detail and facilitate selection. The details might not be "all the information" but enough (e.g., a user-provided mnemonic label) to guide user selection. The browser might also use this information to improve per-instrument pricing.

**Comment by adrianhopebailie** [comment]
I wouldn't call these "payment instruments" but I support the idea of apps being able to register multiple "choices" for the user that reflect different combinations of payment method identifiers.

Apps can use this to reflect the instruments that the user has installed or just to put the choice of payment method or funding source in the initial app selection list.

See also: https://github.com/w3c/browser-payment-api/issues/185#issuecomment-223047965

**Comment by adrianhopebailie** [comment]
The latest payment apps proposal includes the idea of "payment options" which supports this requirement.

A payment app (single endpoint URL) can register multiple payment options (groups of supported payment methods, a single label and icon for user selection).

**Comment by adrianhopebailie** [comment]
Migrated to https://github.com/w3c/webpayments-payment-apps-api/issues/12
