### ISSUE TITLE
[Payment apps] How should third-party payment apps be displayed by the browser?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments#143]
When the user has selected a payment app that has a UI, how should the browser display it? One answer is that this is an implementation detail to be left to the browser.

**Comment by adrianhopebailie** [comment]
I am in favor of leaving this to implementors, but if we don't standardize anything then we force the app to do a lot of work to figure out the context it is being rendered in.

That said, websites must figure that stuff out already today so this is nothing new.

To put a finer point on this I support the spec simply saying: "if the payment app returns text/html the browser should render this to the user"

**Comment by rsolomakhin** [comment]
> To put a finer point on this I support the spec simply saying: "if the payment app returns text/html the browser should render this to the user"

+1

**Comment by tnguyen14** [comment]
> To put a finer point on this I support the spec simply saying: "if the payment app returns text/html the browser should render this to the user"

@adrianhopebailie does that mean running a full website i.e. with JavaScript enabled? Like in an iframe? or is it strictly just text/html?

**Comment by rsolomakhin** [comment]
I'd think a full website with JavaScript.

**Comment by adrianhopebailie** [comment]
> I'd think a full website with JavaScript.

Yes. A normal HTTP response today is just text/html and the browser then makes subsequent calls for additional resources (like images and javascript) because these are linked from the base document.

I'd imagine this being done in the same way.

**Comment by adrianhopebailie** [comment]
The newly proposed invocation model [1] makes it unnecessary to define this. The payment app is Javascript running in the browser and can use `window.open()` to display UI as required.

[1] - https://github.com/w3c/webpayments-payment-apps-api/issues/3
