### ISSUE TITLE
[Payment Request] Should we allow a "polling" mechanism for websites to not invoke the API if there are no enabled methods

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webpayments#159]

**Comment by adrianhopebailie** [comment]
Could be supported by a paymentOption called "noRecommendedApps" or similar

**Comment by webpayments** [comment]
I think there was some discussion that the Apple Pay implementation had a
method to signal if the user can pay using the API.  I was not clear as to
whether this was a method on a payment object, or some global method.  I
feel like a global method would be more interesting - you shouldn't be
creating an object if the user doesn't have any payment methods available.

In any event, this seems like an obvious extension to what we have today
that would add a lot of value - and not just to merchants.  It also feels
like it would be trivial to add for v1 (to me).  And with my testing hat
on, it feels like it would be trivial to test given a controlled
environment.

On Fri, Jul 8, 2016 at 6:29 AM, Adrian Hope-Bailie <notifications@github.com

> wrote:
> 
> Could be supported by a paymentOption called "noRecommendedApps" or similar
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/w3c/webpayments/issues/159#issuecomment-231337615,
> or mute the thread
> https://github.com/notifications/unsubscribe/APFrHHyfREkIgKLGDl2XYrX-jQ0yt-xtks5qTjSzgaJpZM4JH8qf
> .

## 

Shane McCarron
Projects Manager, Spec-Ops

**Comment by adrianhopebailie** [comment]
The discussion in the payment apps breakout revolved around getting a similar function to that offered by ApplePay but also recognising the need to do this in a privacy preserving way.

In the abstract we need a way for a merchant website to say: "Here's my payment request, including all the supported methods, if I call show() right now will the user be prompted to install recommended payment apps to be able to process this payment or have they already got apps installed that can handle this request."

As you can see this fits hand-in-hand with the concept of the browser and merchant being able to recommend payment apps to the user. The desire here is to fail silently (from the perspective of the user) rather than show the user a UI suggesting they install recommended payment apps.

Obviously, if we don't have the idea of recommended payment apps at all then the API would fail silently (from the user perspective) anyway and the website can direct the user to their traditional payment page.

The privacy issue we haven't yet solved is merchants polling the API multiple times with different payment requests to determine what payment methods the user supports. We could conceivably only allow the website to call this once (specifically how this might be done I'm not sure yet)

**Comment by halindrome** [comment]
@adrianhopebailie said:

> The privacy issue we haven't yet solved is merchants polling the API multiple times with different payment requests to determine what payment methods the user supports. We could conceivably only allow the website to call this once (specifically how this might be done I'm not sure yet)

Well - I expect that various implementations will address this by limiting the frequency with which the PaymentRequest object can be created.  Alternately, we could define the object as a singleton - an object for which there can only be one in any given context.  That plus a frequency limitation would help...  

I don't know that there is a way to express an object as a singleton in WebIDL, but it can obviously be expressed in the prose.  @adrianba what would you think about PaymentRequest being a singleton?

**Comment by adrianhopebailie** [comment]
IIRC @adrianba has already said he doesn't want to make PaymentRequest a singleton but that's okay. The privacy problems only start when the website calls `show()`.

I could imagine a mechanism by which if you call `canUserPay()` (or whatever we call this function) and it returns a `true` then we start to restrict things until the merchant calls `show()`.

Or perhaps we stop creation of new PaymentRequests after that has been called on any PaymentRequest? We need to model this a little better I think before we make a concrete proposal

**Comment by jnormore** [comment]
From a merchant perspective, I would want to provide the customer with the most streamlined checkout possible, which IMO would mean that if they don't have a payment type enabled I could make it easy to enable that in the checkout flow itself (for example: paypal sign up before login is the same flow, adding a credit card before storing it is the same flow). If I have to kick the customer off the checkout path it's going to reduce conversion, it's a last resort due to restrictions in the payment method onboarding. You cited Apple Pay as an example, I wouldn't use this as a good example of an ideal case from a merchant or customer perspective, requiring the customer to jump out to a separate application (or multiple) to enable it is really bad for checkout conversion and I'm sure this onboarding experience will be improved upon in the future once the pain is felt.

I say this here because I see some reference to this polling mechanism in place of the ability to recommend payment apps in the payment UI. I think it may be valuable in addition to that but if it's an alternative to that I think it's worth understanding that from most merchants perspectives, having to provide a separate payment method enablement path from the normal checkout path is a deal breaker.

**Comment by adrianhopebailie** [comment]
@jnormore +1

My take on this proposal is that it is in addition to the idea of recommended apps. It makes no sense on its own.

So, the flow would be:
- Merchant requests payment and specifies supported payment methods and optionally recommended payment apps for one or more of these.
- Browser may also recommend apps (perhaps only if the merchant does not?)
- If the user has no available apps then they select one of the recommended apps which is invoked in the same way as if it was being invoked to handle a payment except that the user is able to follow an enrollment/login path before authorizing the payment.
- If the merchant doesn't want the user to be taken down an enrollment path:
  - They can "poll" the API to see if the user is able to handle the request with their registered apps.  
    ALTERNATIVELY
  - The merchant sets a flag in the request that instructs the browser to not show any recommended apps to the user and to fail silently if there are no apps registered that can handle the payment request

**Comment by webpayments** [comment]
I agree that making a user skip out to enable a payment method is overly
onerous.  But surely this is a boot-strapping problem?  And it might be
imagined.  Consider this:
1. Web Payments become available in my favorite user agent and I am invited
   / encouraged to set up a payment app.
2. I set up a payment app.  It encourages me to attach one or more payment
   methods.
3. I attach one or more payment methods (my debit card, my corporate charge
   card, my paypal account).

If a customer came to my site without a registered payment app
(canUserPay() returns false) I _could_ remind them that process is
available... but I don't need to.  It isn't my responsibility as a merchant
to get the eco-system populated.  It is in the interest of the payment app
providers to do that, and I expect they will.  "Use Bob's Wallet for a more
secure checkout!"  That's Bob's job.  Not mine.

On the other hand, if my PSP offers me a better rate when I check out using
more secure methods... I can see it becoming my job.  Or at least in my
best interests.  But I feel like I would still refer my customers to Bob.
Or whatever my favorite Payment App provider was.  I don't want this in my
checkout flow.  I want it to be in place.  If it isn't in place.... I
already have a checkout flow that works and I am not going to mess with it.

Maybe I am missing something.

On Tue, Jul 12, 2016 at 7:59 AM, Jason Normore notifications@github.com
wrote:

> From a merchant perspective, I would want to provide the customer with the
> most streamlined checkout possible, which IMO would mean that if they don't
> have a payment type enabled I could make it easy to enable that in the
> checkout flow itself (for example: paypal sign up before login is the same
> flow, adding a credit card before storing it is the same flow). If I have
> to kick the customer off the checkout path it's going to reduce conversion,
> it's a last resort due to restrictions in the payment method onboarding.
> You cited Apple Pay as an example, I wouldn't use this as a good example of
> an ideal case from a merchant or customer perspective, requiring the
> customer to jump out to a separate application (or multiple) to enable it
> is really bad for checkout conversion and I'm sure this onboarding
> experience will be improved upon in the future once the pain is felt.
> 
> I say this here because I see some reference to this polling mechanism in
> place of the ability to recommend payment apps in the payment UI. I think
> it may be valuable in addition to that but if it's an alternative to that I
> think it's worth understanding that from most merchants perspectives,
> having to provide a separate payment method enablement path from the normal
> checkout path is a deal breaker.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/w3c/webpayments/issues/159#issuecomment-232039369,
> or mute the thread
> https://github.com/notifications/unsubscribe/APFrHBZJiKlFT2t8FrFi8AqjS1J4YAj2ks5qU4-bgaJpZM4JH8qf
> .

## 

Shane McCarron
Projects Manager, Spec-Ops

**Comment by jnormore** [comment]
> That's Bob's job.  Not mine.

I think this is where the difference in opinion is. This is just as much the merchants job as it is Bob's. The merchant wants the customer to have the ability to check out as easily as possible, to sell their products, so it's their job to give them the most seamless way to onboard to those payment methods as possible while not distracting from the original intent to purchase. More than 90% of checkouts on our platform are new customers/new devices/new accounts, which would fall into this first-time experience flow for a lot of payment methods. Not all merchants are major marketplaces, once you get to individual SMBs or even larger merchants with standalone sites return rates are much lower, for example I shop at Amazon almost daily but I shop at Nike maybe only a couple times a year (or whatever shoe store). You can argue that by shopping at one site and setting up your payment method there, the customer no longer has to worry about this on others, but there are a lot of different payment methods out there and new customers/devices/accounts all the time, the first-time experience is more important than I think most people realize.

The case of merchants being incentivized by PSPs to offer them as a preferred checkout method is valid but not the major driver of this for me.

I didn't mean to hijack this thread for this, it's off-topic for sure :)

**Comment by nickjshearer** [comment]
> If the merchant doesn't want the user to be taken down an enrollment path:
> 
> They can "poll" the API to see if the user is able to handle the request with their registered apps.

I'm wondering in this scenario what prevents the merchant from simply polling the API constantly with a differing list of registered apps, in an attempt to divulge the registered payment applications a user has. Would I be correct in assuming merchants couldn't invoke this polling until they called show?

**Comment by adrianhopebailie** [comment]
@nickjshearer this is a problem we would need to solve. See earlier in the thread for some thoughts. 

> The privacy issue we haven't yet solved is merchants polling the API multiple times with different payment requests to determine what payment methods the user supports. We could conceivably only allow the website to call this once (specifically how this might be done I'm not sure yet)

Smart solutions invited...

**Comment by tommythorsen** [comment]
I think a polling mechanism is a good idea, but the browser needs to get the user's consent before handing this information over to the merchant (just like when asking permission for a web site to use the location api for instance).

This means that when the merchant calls the polling function, a dialog will be displayed saying something like "The website 'abcmerchant.com' wants to access your payment apps. Allow / Deny".

I'm not sure whether this should be a permission to use the entire payments api, or just the polling function. A permission for the entire payments api might be the better choice.

**Comment by ianbjacobs** [comment]
I think I am +1 to @tommythorsen:
- polling mechanism that returns a boolean whether the user has any registered payment apps (including browser-stored credentials). This polling mechanism WOULD NOT allow the merchant to ask about specific payment methods or apps, simply whether there has been any registration at all.
- user consents to the provide the answer. 

Ian

**Comment by adrianhopebailie** [comment]
This feels like something that should be logged against PaymentRequest. Can I close this and log it there instead?

**Comment by ianbjacobs** [comment]
It doesn't feel to me like a paymentRequest functionality. I see the flow working this way (potentially) from the merchant's perspective:

1) Does the user's browser support these APIs? If no, fail (which means traditional checkout page here and every time I write "fail" below).
2) Does the user have any apps? If no, fail.
3) Call payment request. Are there any matching apps? If no, fail.
    Otherwise, get payment data from app.

So it seems to me that question 2 is outside the scope of payment request API, or at least could be, and thus could be specified separately. I would argue that we should get agreement on the sort of 1-2-3 flow (which I hope to write up separately, btw) before deciding "this goes into payment request API".

Ian

**Comment by tommythorsen** [comment]
@ianbjacobs 

> polling mechanism that returns a boolean whether the user has any registered payment apps (including browser-stored credentials). This polling mechanism WOULD NOT allow the merchant to ask about specific payment methods or apps, simply whether there has been any registration at all.

I feel that such a polling mechanism adds very little value. If we want a polling mechanism, we should have one that allows the merchant to check whether the user has a matching payment app installed. I think it's fine that the mechanism lets the merchant extract sensitive information about installed apps, as long as the user has given consent first.

**Comment by ianbjacobs** [comment]
The reason I call this one out as distinct from the "is my app installed?" query is that I think there are two motivations:
- Should I bother with the API / experience at all? (Because the user has NO apps)
- Should I do something special related to me (Because the user has MY app)

For the moment I think it's valuable to tease these apart. Whether we want 0, 1, or 2 APIs should be informed by other parts of this discussion.

Ian

**Comment by burdges** [comment]
These sorts of API queries sound like a serious security flaw.  

I'd think the merchant should just invoke the API and then continue on as if the API did not exist.  If the API works, then it should shut down the merchant page completely, transferring the user to the payment mediator selector thing, which lets the user select the payment app, and transfers control there.  

We should presumably let the back button work in the payment mediator of course, presumably restoring the previous merchant page, thus allowing them to present payment options in their old way.

In principle, a browser vender might wish the payment mediator to present itself in parallel with the existing page.  I think that's rather dangerous because it might evolve towards a flawed security model, but seems not intrinsically broken.

**Comment by sideshowbarker** [comment]
I think all of @jnormore’s comments in this thread are worth paying very careful attention to; e.g.:

> From a merchant perspective, I would want to provide the customer with the most streamlined checkout possible, which IMO would mean that if they don't have a payment type enabled I could make it easy to enable that in the checkout flow itself
> ...
> You cited Apple Pay as an example, I wouldn't use this as a good example of an ideal case from a merchant or customer perspective, requiring the customer to jump out to a separate application (or multiple) to enable it is really bad for checkout conversion
> ...
> The merchant wants the customer to have the ability to check out as easily as possible, to sell their products, so it's their job to give them the most seamless way to onboard to those payment methods as possible while not distracting from the original intent to purchase

I do not think the importance of the overall point that @jnormore is making here can be overstated.

We all are here to solve problems for end users ultimately, and IMHO we should always be careful in everything we do to preserve the primacy of user experience over other concerns. 

Solutions that help to address problems for other non-user constituencies involved are net bad on balance if the cost of them is that they degrade the user experience or disrupt or intrude into the normal user interaction/expectations for sites/services they want to get something done with.

**Comment by halindrome** [comment]
@sideshowbarker said:

> Solutions that help to address problems for other non-user constituencies involved are net bad on balance if the cost of them is that they degrade the user experience or disrupt or intrude into the normal user interaction/expectations for sites/services they want to get something done with.

Yes!  Yes and yes!  Of course the end user should have the least pain. If it ever seemed like I was not advocating for that, thank you for giving me the opportunity to correct the record.

The greatest number of users should have the least amount of pain.  Conversely, the smallest number of affected people (e.g. implementors) should be prepared to deal with some inconvenience so that the greater number of people _can_ experience the least amount of pain.  

I don't think anyone involved with this activity would disagree with these precepts.

With regard to the current discussion topic... Maybe I am just being obtuse here.  I agree that onboarding needs to be as seamless as possible.  But that's a UI and flow design issue.  I am not clean what that has to do with the app that is being installed calling a "register" interface to inform the environment it is available.  

If the argument is that users shouldn't have to register anything... well, that's confusing to me.  Surely a user needs to do all sorts of things to configure a payment app the first time it is used?  Agree to install it, teach it about a payment instrument, teach it their address(es).  Yes, that's a hurdle.  Should it be low?  Of course.  But it's going to be there.  I feel like I am missing something.

**Comment by msporny** [comment]
> I feel like I am missing something.

You're not the only one. I've been quietly monitoring this issue and it's clear to me that 3rd party payment app registration is very strong requirement.

Clearly we all want the customer experience to be excellent, but in order for that to happen, some setup is required. That said, I feel like this thread is going a bit off topic. The question was around polling to see if a user can pay using the API, not whether or not we want to support registration of 3rd party payment apps (which we do).

**Comment by halindrome** [comment]
Thank you for pulling this back on track!

**Comment by ianbjacobs** [comment]
Subsumed by https://github.com/w3c/browser-payment-api/issues/310
