### ISSUE TITLE
[Payment Apps] What is the process for rendering the payment app UI

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webpayments#162]
When the payment app requires UI it provides a URL that must be fetched to render UI.

WebRTC does this by rejecting the original calling page's promise with a URL which is rendered.
This seems like a problem (asking the merchant to render the app).

Better option may be a simple `window.open()` from the payment app javascript code.

**Comment by adrianhopebailie** [comment]
Migrated to https://github.com/w3c/webpayments-payment-apps-api/issues/4

**Comment by mksbrick48** [comment]
I got no idea what this is
