### ISSUE TITLE
[Payment App] Should the payment app registration be for Browsers only or also for other types of User Agents

### ISSUE THREAD

**Issue by LaurentCastillo** [w3c/webpayments#165]
Using things like javascript to handle invocation might limit the specification to Browser only.

**Comment by cyberphone** [comment]
@LaurentCastillo Indeed.  I would assume that native apps which can be used in many different scenarios would rather be automatically discovered by the browser when using the Web in the same way as they must be automatically discoverable when used with NFC.

**Comment by adrianhopebailie** [comment]
The approach right now is to have a spec specifically for the browser (i.e. Payment App API).

Also, we are limiting ourselves to only specifying a Web-based integration (i.e. via Web technology) but that does not preclude platforms (like iOS, Android, Windows Phone etc) from providing a way to register apps through an alternative channel.

**Comment by adrianhopebailie** [comment]
The Payment Apps API spec is specifically for browsers therefor I am closing this issue and not migrating it to that repo.
