### ISSUE TITLE
3D secure support

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [w3c/webpayments#217]
Hi,

I haven't read yet in specifications 3D secure support, so i'm trying to imagine how 3D secure should be supported in web payments.

Current version of 3D secure is handled throught redirection 
- User fill up his card details, and submit 
- Psp detects if card is enrolled by 3D secure
- If yes, user is redirected to bank ACS, where he fills out authentifications informations
- User is then redirected to PSP, which can process the payment (with cards details and 3D secure stuffs)

3D secure authentification required 
- Access to all banks (is this card enrolled, which address to redirect the payee)
- A way to redirect user, and provide him a form      

Which component should be responsible to handle 3D secure ?
A pay app could take this responsibility, but it must be connected to banks
Or should we imagine, a new process letting the merchant manage the window according PSP results (if PSP returns  that 3D secure authentification is needed, merchant could redirect user in the window)..

_============ 3D secure version 2
There is already a draft explaining how 3D secure version 2 works.. redirection should not be mandatory because they will supply SDK's to handle authentification.
I think, we whould not focus on this version yet._

What do you think ?
Thanks,
Nelson

**Comment by ianbjacobs** [comment]
I believe it's payment apps. Closing the issue for now.

**Comment by Abacaxi-Nelson** [comment]
@ianbjacobs should i open it on dedicated repo ?
3D secure is a use case we should cover.

**Comment by ianbjacobs** [comment]
@tugal, 

Please do not open a new issue at this time.

**Comment by adrianhopebailie** [comment]
@tugal - 3D Secure will be handled in exactly the same way as it is today.

If the payment method is "basic-card" then the merchant/processor must still submit the card details for processing in the same way they would if the details were submitted via a web form. If the response is a redirect then the user will be redirected.

Likewise, for a payment app. If the payment is processed within the app and it is a card payment that requires 3D secure then the app must display a window that renders the redirect URL. (same as if you use an native mobile app to do a payment using 3D secure today.
