### ISSUE TITLE
Sepamail WebIDL syntax and algorithms

### ISSUE THREAD

**Issue by rsolomakhin** [w3c/webpayments#219]
I suggest the following changes in in [sepamail proposal](https://w3c.github.io/webpayments/proposals/sepamail):

1. The type of `supportedNetworks` should change from `sequence` to `sequence<DOMString>`.
1. The type of `supportedTypes` should change from `sequence` to `sequence<BasicSepamailType>`.
1. The name of `SelectedNetwork` should change to `selectedNetwork`.
1. The name of `SelectedType` should change to `selectedType`.

Also, please add some algorithms to process `BasicSepamailRequest` in the browser. At the very least, please specify what should happen if `supportedNetworks` or `supportedTypes` is an empty list. What should happen if `supportedNetworks` contains empty or duplicate strings. (I suggest throwing TypeError in all those cases.)

**Comment by marcoscaceres** [comment]
sepamailIdentifier should just be "id"

**Comment by ianbjacobs** [comment]
I believe Cyril has integrated comments: 
https://w3c.github.io/webpayments/proposals/sepamail.html

(Cyril has asked Rouslan to verify.)

**Comment by rsolomakhin** [comment]
Looks good, thank you.

**Comment by ianbjacobs** [comment]
We have not worked on the sepamail proposal for a long time so closing this for now.
