### ISSUE TITLE
Merge Payment Request Architecture with Capabilities Document

### ISSUE THREAD

**Issue by msporny** [w3c/webpayments#22]
From the [Payment Request Architecture](http://wicg.github.io/paymentrequest/specs/architecture.html#abstract) document:

> The Payment Request architecture is designed to separate different concerns of the Payment Request system into different specifications so that they can be discussed and moved forward independently. This document describes the architecture and explains what different specifications may be created and how the relate to each other. [[link](http://wicg.github.io/paymentrequest/specs/architecture.html#abstract)]

It feels like the Payment Request Architecture and the Web Payments IG's Capabilities document overlap (based on the desired goals for the capabilities document). I agree that we need a document like the Payment Request Architecture, but think that it should be placed into the architecture document (capabilities) the WPIG agreed upon.

Spec refs:
http://wicg.github.io/paymentrequest/specs/architecture.html#abstract

**Comment by adrianhopebailie** [comment]
Good idea. This can happen once the WG has agreed on the content.

**Comment by ianbjacobs** [comment]
+1 to fostering the WG discussion and then bringing it in as we can.

**Comment by msporny** [comment]
Migrated to https://github.com/w3c/browser-payment-api/issues/42
