### ISSUE TITLE
Adopt a "test as you commit" policy

### ISSUE THREAD

**Issue by rakuco** [w3c/webpayments#234]
An increasing number of groups are beginning to make web-platform-tests part of their day-to-day work, and more are considering it, for example in w3c/dap-charter#48. https://github.com/foolip/testing-in-standards/blob/master/policy.md has some additional context, and https://github.com/w3c/accelerometer/pull/29 is an example of the changes we've been landing.

I can see that the payment-requests repository already has something similar in place in https://github.com/w3c/payment-request/blob/gh-pages/test-plan.md; I was wondering if you'd be open to doing the same to the other repositories:
* payment-method-id and payment-method-basic-card seem to be tested mostly via [payment request](https://github.com/w3c/web-platform-tests/tree/master/payment-request). I was thinking of adding a section to their `CONTRIBUTING.md` pointing to payment-request's `test-plan.md`, but using the boilerplate text we've been adding to other specs should also be fine.
* payment-handler seems to be being tested separately in [w-p-t](https://github.com/w3c/web-platform-tests/tree/master/payment-handler), so adding the usual text to its `CONTRIBUTING.md` should be fine.

**Comment by marcoscaceres** [comment]
Just noting the payment request test plan is not great (doesn't actually cover what we do)... The WHATWG work mode cover things better: https://whatwg.org/working-mode

**Comment by marcoscaceres** [comment]
@rakuco, we are trying to do what mentioned above here: https://github.com/w3c/wg-effectiveness/issues/21

Could definitely use some help with that to help make it a W3C wide policy! It will take time, but a lot of us a trying to name it happen.

**Comment by rakuco** [comment]
That seems to be in line with what @foolip and I have been trying to do by adding the "test as you commit" policy to multiple specs lately, so I think we're all on the same page here. In this case, do you have any objections to what I outlined above?

**Comment by foolip** [comment]
@marcoscaceres, will this be a discussion at TPAC? Can I observe the session?

**Comment by marcoscaceres** [comment]
Let's just find a time to chat on Wednesday? There are a few talks happening around testing then.

**Comment by foolip** [comment]
Sure. There's a breakout session about web-platform-tests then, but I'll come to wherever the discussion is. (I'm flying on the afternoon though.)

**Comment by foolip** [comment]
@marcoscaceres, is the group having a meeting on Wednesday? I guess the group needs to make a resolution on this?

**Comment by marcoscaceres** [comment]
If you mean Payments, we are meeting today... but there is no need for a resolution - it's now basically baked into our process as all the editors agreed to do it.

**Comment by ianbjacobs** [comment]
I believe this is a policy that the editors of various specs have adopted; closing.

**Comment by marcoscaceres** [comment]
Agree! It’s been a really great shift and wonderful to see it working well.
