### ISSUE TITLE
Document relationship diagrams?

### ISSUE THREAD

**Issue by msporny** [w3c/webpayments#24]
I like the [document diagram](http://wicg.github.io/paymentrequest/specs/architecture.html#architecture) in the Payment Request Architecture document. This diagram should probably go in the capabilities document as the capabilities document is supposed to tie everything together across IGs/WGs.

Spec refs:
http://wicg.github.io/paymentrequest/specs/architecture.html#architecture
http://wicg.github.io/web-payments-browser-api/#how-this-document-is-organized

**Comment by adrianhopebailie** [comment]
@pat-adler This issue has gone a stale but I trust you are on top of keeping the capabilities doc in sync with the WG work as you see fit.
