### ISSUE TITLE
Just a question, curious

### ISSUE THREAD

**Issue by jehan96** [w3c/webpayments#249]
i am curious to know, 
i tested several example of the usage of Payment Request API..
when i try the buy now..
and complete purchasing (using fake card of course)
i did not receive any email about confirming the payment...
it makes me think, they don't want to implement that feature or it is not there?
if not there, is there any way to email buyer about the confirmation order with receipt?
does PR API has something like order.completed method so that after order was placed, we can then update inventory somewhere (for example square P.O.S or custom build)

but the main case here, the email...can we trigger email after order completed?

**Comment by ianbjacobs** [comment]
Hi @jehan96,

Payment Request API currently only addresses data gathering. How the merchant and customer interact for other parts of the transaction (such as confirmation and receipt) are not covered by the API and would presumably be addressed as they already happen today. 

For example, the merchant can share status information in a variety of ways:

 * Via a Web page in response to the PR API complete().
 * By using an email access collected via PR API.
 * Via the transaction history in the user's account with the merchant.

From time to time we do discuss extensions to the API, or other APIs that might address the other phases of a transaction. But at this time we are not actively working on them.

I hope that helps,

Ian
