### ISSUE TITLE
Specify both pickup and delivery addresses in a single payment request

### ISSUE THREAD

**Issue by nalakadg** [w3c/webpayments#252]
Hi, 

Does the payment request standard cater for the specification of both a pickup and delivery addresses in a single payment request? 

thanks
Nalaka

**Comment by ianbjacobs** [comment]
Hi @nalakadg,

Right now PR API does not support mixed delivery options in a single order.

That topic has come up previously; I will link to this issue from our list of candidate features:
 https://github.com/w3c/payment-request/wiki

Thanks!

Ian

**Comment by ianbjacobs** [comment]
We removed address information from PR API, so closing.
