### ISSUE TITLE
Should we have separate specifications for payment and registration of payment apps?

### ISSUE THREAD

**Issue by msporny** [w3c/webpayments#26]
The [Payment Request Architecture diagram](http://wicg.github.io/paymentrequest/specs/architecture.html#architecture) suggests that we split registration from payment. While I agree that the separation of concerns is good and helps both progress independently, I'm concerned that it also creates a very easy excuse for us to ignore the registration problem and may accidentally create an oligopoly in which the browsers and OS vendors control who can and can't register.

While I don't think any one of us wants to create an oligopoly, ignoring the registration problem is something that has a moderate chance of creating such an oligopoly. For example: "BigCorp requires all registering payment instruments to pass our payment instrument criteria (which, by the way, requires your payment instrument to have a total transaction volume of X, for you to pay us registration fees, and for your company to have existed for 10 years and have at least a millions of dollars in recurring revenue)".

So, if we split these specs, I'd only be okay if we commit to similar time frames.

To be clear, the registration process has several good technical approaches we could utilize:
1. Shared, centralized corporate community run registry.
2. Decentralized WebDHT-based mechanism.
3. Decentralized payment instruments as credentials.
4. Password-manager as registration vehicle (LastPass, etc.)

... and you can't do a payment until there is some registration process available (and polyfill-able).

Spec refs:
http://web-payments.github.io/web-payments-messaging/#payment-instrument-registration
http://wicg.github.io/web-payments-browser-api/#payment-instrument-registration
http://wicg.github.io/paymentrequest/specs/architecture.html#payment-method-registration-specifications
http://wicg.github.io/paymentrequest/specs/method-identifiers.html#issue-3

**Comment by adrianhopebailie** [comment]
:+1: for keeping these in the same spec.

I believe one of that ways registration can (and should) be done is via the browser API and so it makes sense for this to be part of that specification.

**Comment by msporny** [comment]
Migrated to https://github.com/w3c/browser-payment-api/issues/12.
