### ISSUE TITLE
Proposal to restore charter text around UI being out of scope

### ISSUE THREAD

**Issue by hober** [w3c/webpayments#262]
The [current charter](https://www.w3.org/Payments/WG/charter-2022.html) dropped the following two sentences from [§2.1 Out of Scope](https://www.w3.org/Payments/WG/charter-2022.html#out-of-scope) that were present in the [previous charter](https://www.w3.org/Payments/WG/charter-201912.html) ([diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FPayments%2FWG%2Fcharter-201912.html&doc2=https%3A%2F%2Fwww.w3.org%2FPayments%2FWG%2Fcharter-2022.html)):

> User interface specifics are out of scope; this Working Group is chartered to Recommend programming interfaces, not user interface specifics. However, it is in scope for the Working Group to discuss user experience, for example as part of understanding user journeys during a checkout experience.

My understanding from chatting with @ianbjacobs is that this change was made to facilitate some requirements in SPC, but it's unclear to me if such a change was actually necessary to enable SPC to contain those requirements. Many web platform specifications contain requirements that touch on the user experience while staying away from user interface specifics, e.g. the [show a notification](https://notifications.spec.whatwg.org/#showing-a-notification) steps require **that** a notification be displayed but does not say **how** notifications are displayed.

If it's agreeable to the working group, I'd be happy to prepare a PR for the charter that restores this text. I'm not sure which repo the charter text lives in, though.

**Comment by ianbjacobs** [comment]
@hober, we'll have a look at this at our upcoming meeting. Thanks!

**Comment by adrianhopebailie** [comment]
@hober can you expand on why this is important?
Do you have concerns about specific work that the WG is doing that, in your opinion, should be considered out of scope?

**Comment by hober** [comment]
> @hober can you expand on why this is important?

In general, web standards shouldn't constrain innovation and differentiation in user interfaces.

> Do you have concerns about specific work that the WG is doing that, in your opinion, should be considered out of scope?

Not offhand, but I haven't looked recently.

**Comment by ianbjacobs** [comment]
This issue was mentioned in [the minutes of Web Payments Working Group – 27 March 2023 ](https://www.w3.org/2023/03/27-wpwg-minutes.html#)

**Comment by adrianhopebailie** [comment]
> In general, web standards shouldn't constrain innovation and differentiation in user interfaces.

Nothing in the current charter suggest that the group is going to develop Web standards that do constrain innovation and differentiation.

The group is working to develop technologies (like SPC) that must operate within specific constraints imposed by legislation (e.g. Secure Customer Authentication) in order to be useful. The standards defining these technologies MUST specify **properties** of the UI that are necessary for the technology to meet these legal requirements (i.e. it doesn't specify the UI itself or constrain innovation and differentiation). 

The text that you have proposed would prevent the WG from publishing standards that are actually useful.

**Comment by adrianhopebailie** [comment]
Alternative new charter text which will not prevent the WG producing useful recommendations that can align with legal and regulatory requirements. Additions in **bold**

> User interface specifics are out of scope; this Working Group is chartered to Recommend programming interfaces, not user interface specifics. **However, some Recommendations from this Working Group will define interactions between programming interfaces and user interfaces which may imply requirements on the user interfaces. There may be cases where these user interface requirements are influenced by relevant legal or regulatory requirements and in these cases the Recommendations will provide guidance on user interface specifics without making them normative requirements.** It is also in scope for the Working Group to discuss user experience, for example as part of understanding user journeys during a payment experience.

**Comment by ianbjacobs** [comment]
Thanks @adrianhopebailie. Rather than "will provide guidance" I would say "may provide guidance."

@hober, would you mind providing some feedback on whether this proposal from Adrian would work from your perspective?

Thanks!

**Comment by ianbjacobs** [comment]
A call for consensus is underway:
 https://lists.w3.org/Archives/Public/public-payments-wg/2023Apr/0011.html

**Comment by hober** [comment]
> The group is working to develop technologies (like SPC) that must operate within specific constraints imposed by legislation (e.g. Secure Customer Authentication) in order to be useful. The standards defining these technologies MUST specify **properties** of the UI that are necessary for the technology to meet these legal requirements (i.e. it doesn't specify the UI itself or constrain innovation and differentiation).

I don't think a spec should make normative claims about what may or may not meet legal requirements.

> The text that you have proposed would prevent the WG from publishing standards that are actually useful.

This is untrue, so far as I can tell.

**Comment by ianbjacobs** [comment]
This has been completed. The revised charter was announced on 3 August.

**Comment by NavinPa** [comment]
https://developers.googleblog.com/2024/02/federated-credential-management-migration-for-google-identity-services.html
