### ISSUE TITLE
Confining the definition of user agents to browsers

### ISSUE THREAD

**Issue by msporny** [w3c/webpayments#34]
The Web Payments WG charter currently states that we're to work on deliverables for "user agents":

http://www.w3.org/Payments/WG/charter-201510.html#deliverables

It is clear that one of these user agents is a browser and the payment request work strongly binds to that concept by pulling in requirements like HTML5, DOM4, and ECMA-262 6th Edition:

http://wicg.github.io/paymentrequest/specs/paymentrequest.html#dependencies

There are many other types of user agents than just browsers. It could be argued that we're not fulfilling our charter if we deliver only the interfaces as defined in paymentRequest. To put this another way, if the charter stated that the WG is confined to just 'browsers', I expect that there would have been multiple formal objections to the charter.

I'm asserting that we need to consider an API that works for user agents that are not browsers (and instead demonstrate bindings to something more common across user agents like an HTTP API):

http://web-payments.github.io/web-payments-http-api/

This is not to say that we shouldn't also have APIs for browsers, but browsers are not the only deployment targets here. Is an HTTP API in scope for this WG?

**Comment by ianbjacobs** [comment]
Is this the same as issue 17?
 https://github.com/w3c/webpayments/issues/17

**Comment by msporny** [comment]
Yes, it is. Closing it. Thanks @ianbjacobs
