### ISSUE TITLE
PROPOSAL: Hold WG meetings every week until further notice.

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webpayments#58]
Per the discussion on the mailing list [1].

> Our original intent was to meet weekly but alternating between “Americas” friendly times and “Asia Pacific” friendly times...
> ...despite having run the questionnaire twice, we only have responses from two people, only one of whom is in the AP region. [2]

PROPOSAL:

The group moves to a weekly conference call schedule in our current time slot (Thursdays at 17:00 UTC) with the chairs running a biweekly “catch up” session at an Asia-Pacific friendly time if requested by the group. 

[1] https://lists.w3.org/Archives/Public/public-payments-wg/2016Jan/0058.html
[2] https://www.w3.org/2002/09/wbs/83744/WGconfschedule_eastern/results

**Comment by adrianhopebailie** [comment]
RESOLVED by consensus on the call on 21 January

**Comment by msporny** [comment]
Hey @adrianhopebailie,

When resolving proposals, please note the exact resolution text so there is no confusion as to exactly what got resolved (most everyone forgets the details 2-3 months after the fact). In addition, PROPOSAL text is often changed during the straw polling period in a call. So, the above should read:

RESOLVED by consensus at [21 January 2016 teleconference](https://www.w3.org/2016/01/21-wpwg-minutes.html): The group moves to a weekly conference call schedule in our current time slot (Thursdays at 17:00 UTC) with the chairs running a biweekly “catch up” session at an Asia-Pacific friendly time if requested by the group.
