### ISSUE TITLE
Terminology for payer/payee, user/merchant, debtor/creditor

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webpayments#59]
The flows task force have been working on defining a normalized set of terminology for the flows and have identified a particular set of terms that require normalization.

To date the WG has used the terms **payer** and **payee** to identify the sending and receiving parties in a payment respectively. Many discussions and documents use the terms **user** and **merchant** as these are the most common specializations of these roles however the ISO20022 terms are **debtor** and **creditor**.

**Comment by adrianhopebailie** [comment]
:+1:  for debtor and creditor

The group resolved to use ISO20022 terminology where appropriate. One caveat is that this langaue may be confusing in examples or specs so we should consider labels like _merchant(debtor) website_, _user(creditor) payment app_ and _user(creditor)'s browser_ in examples and use cases. I think we can get away with simply using debtor and creditor in normative sections of the spec.

**Comment by vkuntz** [comment]
+1 for debtor and creditor
Based on the approach of participants and business roles defined in ISO 20022, we will surely be able to map the specific terminology defined in the current flows with the Creditor/Debtor business roles.

**Comment by webpayments** [comment]
+1 for debtor and creditor.  However, I also endorse Adrian's idea that we
use more common terms in labels for clarity to people who are not in the
industry.

On Wed, Jan 20, 2016 at 8:19 AM, Vincent Kuntz notifications@github.com
wrote:

> +1 for debtor and creditor
> Based on the approach of participants and business roles defined in ISO
> 20022, we will surely be able to map the specific terminology defined in
> the current flows with the Creditor/Debtor business roles.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/webpayments/issues/59#issuecomment-173217063.

## 

-Shane

**Comment by dlongley** [comment]
+1 to Shane's comments (Adrian's idea): https://github.com/w3c/webpayments/issues/59#issuecomment-173223264

**Comment by LaurentCastillo** [comment]
+1 for debtor / creditor associated with common terms

**Comment by mountainhippo** [comment]
I think debtor and creditor is ok, but will but a tough sell in communicating this to existing merchants and payment providers, who will talk in terms of payer/payee or more commonly merchant and customer.

So +1 to @adrianhopebailie 's suggestion to use labels for clarity.

**Comment by bifurcation** [comment]
I agree with @mountainhippo that debtor/creditor is likely to be pretty opaque for a certain slice of users.  But the same will be true of any choice.  The only way out here is to anchor in ISO 20022 and provide synonyms.

**Comment by ianbjacobs** [comment]
+1 to ISO 20022 plus synonyms.

**Comment by webpayments** [comment]
+1 to ISO 20022 plus synonyms.
Cyril VIGNET
+33622040856
+33158400234
Cyril.vignet@bpce.fr

De : ianbjacobs [mailto:notifications@github.com]
Envoyé : mercredi 20 janvier 2016 17:51
À : w3c/webpayments
Cc : webpayments
Objet : Re: [webpayments] Terminology for payer/payee, user/merchant, debtor/creditor (#59)

+1 to ISO 20022 plus synonyms.

**Comment by mattsaxon** [comment]
+1 to ISO20022 plus synonyms;

So some example will be;

Creditor [Merchant/Payee]
Creditor Agent [Merchant/Payee's Payment Service Provider(PSP)]
Debtor [Shopper/Payer]
Debtor Agent [Shopper/Payer's Payment Service Provider(PSP)]

If we can shoot for a consensus agreement to this on tomorrow call, we can update the suggestions in the Wiki that Laurent kindly drafted post the call
https://github.com/w3c/webpayments/wiki/ISO-20022-definitions-mapping-on-flows

**Comment by msporny** [comment]
-1 I think this is a really bad idea. The audience for the spec (Web Developers) don't know what a 'creditor agent' or even what a 'creditor' really means... appending it to "merchant (creditor)" is not good either because it puts aliases beside every term in the spec, making the spec that much harder to read. I suggest we instead do use ISO20022, but put the alias in the definition of what a "merchant" or a "payee" is. 

That way, you get to align w/ ISO20022, you use terminology that Web developers are somewhat familiar with, and you don't make the spec text any more dense than it has to be.

**Comment by adrianhopebailie** [comment]
Closing as the related proposal was resolved on the call on 28 January.
