### ISSUE TITLE
PROPOSAL: Adopt ISO20022 terminology for payer and payee and use synonyms as appropriate

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webpayments#62]
This proposal is an attempt to resolve the question raised in #59.

PROPOSAL:

In keeping with the WG resolution to try and root our terminology in the ISO20022 data dictionary the WG will adopt the following terms for use in its deliverables:
- **Creditor** [Merchant/Payee]
- **Creditor Agent** [Merchant/Payee's Payment Service Provider(PSP)]
- **Debtor** [Shopper/Payer]
- **Debtor Agent** [Shopper/Payer's Payment Service Provider(PSP)]

The WG will supplement these terms with appropriate synonyms as appropriate in order to provide clarity of meaning for the target audience.

Examples: 
- _"The merchant (creditor) website might store the ..."__
- _"The buyer (debtor) will register a payment app issued by their bank (debtor agent) ..."__

**Comment by msporny** [comment]
-1 While I support an attempt to align with ISO20022, and while the ISO20022 terminology is technically accurate, the terminology of 'creditor' and 'debtor' is so foreign to Web developers and the general public that I'm very concerned that we'll completely miss our audience.

COUNTERPROPOSAL: We adopt the ISO20022 language, but use 'payer' and 'payee' in the specs. The definition of 'payer' and 'payee' in the specs should reference the ISO20022 definition of 'creditor' and 'debtor'.

**Comment by adrianhopebailie** [comment]
I would argue that the terminology of 'payer' and 'payee' are equally foreign to a developer audience. Those terms have been used within this group extensively and so feel familiar.

For the majority of use cases 'user' and 'merchant' are most appropriate but these roles are too specialized for our needs.

**Comment by mattsaxon** [comment]
A revisied proposal that Cyril, Laurent, Vincent, Kris discussed today and recommend as a revised proposal is;

This proposal is an attempt to resolve the question raised in #59.

PROPOSAL:

In keeping with the WG resolution to try and root our terminology in the ISO20022 data dictionary the WG will adopt the following terms for use in its deliverables:

<b>W3C WebPayments Term</b> (Common Terms) [ISO 20022 definition]

examples would be;
- <b>Payee</b> (Merchant) [Creditor|Beneficiary]
- <b>Payee PSP</b> (Acquirer/Gateway) [Acquirer|Intermediary]
- <b>Payer</b> (Shopper/Consumer/User) [Debtor|Initiator]
- <b>Payee PSP</b> (Wallet) [Intermediary]

We would the W3C Payments Terms in the W3C specifications (to avoid writing out in detail)
In the flows we would use the complete terms, however it should be realised that Common terms and ISO 20022 definitions may change between flows, for example for Direct Debit the ISO20022 term is Beneficiary, whilst for Credit Transfer it is Creditor.

We will endeavour to have the W3C Terms added to the ISO repository as reserved words or ideally as specific mappings, e.g. a Payee is the superclass of both the subclasses of Creditors and Beneficiary.

What this exercise has shown (me at least) is that these definitions are likely to evolve as we balance understandability and standardisation during the course of our work.

**Comment by kketels** [comment]
In ISO 20022, Participants (which is what we re talking about here) trace to the BusinessRole from which they are derived. A BusinessRole is the more generic term to which many Participants trace to, depending on the context in which they are used. E.g. in the Cards business, we use different names to identify payer/payee i.e. merchant/acquirer. So we can apply this mechanism for web payments too, if need be.  The Harmonisation TF would ensure these web payments businessTransactions are submitted to ISO 20022. From a Message / API point of view, there is a difference: the elements used in e.g. the ISO 20022 Credit Tf message cannot be changed as they must apply for any context (be it cards, cash settlement, web payments,...)  in which Credit Tf message is used..

**Comment by msporny** [comment]
To be clear, I think that we have consensus that we want to align with ISO20022 (no one is arguing against that).

My point is that the W3C spec needs to use more common language (targeted at Web Developers) - and there is disagreement on what that common language should be. The only way we're really going to be able to resolve this is to get some data on it - we need to do a survey w/ Web developers to see which terms they want to use (or find familiar). I can volunteer to do that. I know this is going to take a lot of time, and I don't want to slow down the process with it. 

So, let's have the group make a call on what they want to do ASAP. In parallel, we'll create a survey and collect data for 3-4 months to see what Web developers find familiar. Once we have that data, we may re-open the issue if the data shows that we made the wrong decision.

**Comment by ianbjacobs** [comment]
See:
ISO 20022 definitions mapping on flows
https://github.com/w3c/webpayments/wiki/ISO-20022-definitions-mapping-on-flows

**Comment by msporny** [comment]
@mattsaxon 

Your proposal is unclear wrt. where the changes would be made. Here's what I suggest:
1. We do the WPWG Term/Common Terms/ISO20022 alignment in the WPIG Glossary.
2. The WPIG Glossary is automatically pulled into the specs (this already happens today).
3. We use the term "payee" and "payer", or whatever the W3C Web Payments Term is in the specs.

The flows can use the more specific terminology, if that's what that Task Force wants (and I can see a good reason to do that in the Flows, but not in the specs, which are supposed to be more generalized).

**Comment by adrianhopebailie** [comment]
UNRESOLVED

The WG agreed to revise this proposal and table it again for our next meeting on 28 January.
Discussion continues in the thread at #59 
A new proposal will be logged for consideration in the 28 January WG meeting.

**Comment by mattsaxon** [comment]
@msporny, is Adrian's reword of this here acceptble to you? https://github.com/w3c/webpayments/issues/67

**Comment by msporny** [comment]
@mattsaxon thanks for the ping, yes, reword is good, with one added bullet point to how we implement the proposal in #67. I'm a +1 for the proposal, now.

**Comment by fredMeignien** [comment]
Today's words reflects the way payments work in existing infrastructures and technologies.
Are these words really fitted in the new framework of "WebPayments" ?

For instance, what is an "acquirer" or an "acceptor" in the future world ?
Or what is the word for an entity managing "connectors", "ledgers" or "notaries" in the existing "schemes" ?

New concepts will generate new wording !

We can only trust the words that express a function: for instance, "Payer" and "Payee" are stable concepts (they just say where the money comes FROM and go TO), whilst "Debtor" and "Creditor" depend on legal consideration.

So it would be interesting to use words which directly express the function we want to highlight.
