### ISSUE TITLE
PROPOSAL: Adopt developer friendly-terminology for WG deliverables but root this in ISO20022 data dictionary through our published glossary.

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webpayments#67]
Follows discussion of the question at #59.

PROPOSAL (from @mattsaxon )

In keeping with the WG resolution to try and root our terminology in the ISO20022 data dictionary the WG will adopt the following terms for use in its deliverables:

| W3C Web Payments Term | Common Terms | ISO 20022 definition |
| --- | --- | --- |
| Payee | Merchant | Creditor, Beneficiary |
| Payee PSP | Acquirer, Gateway | Acquirer, Intermediary |
| Payer | Shopper, Consumer, User | Debtor, Initiator |
| Payer PSP | Wallet | Intermediary |
- We will use the W3C Payments Terms in the W3C specifications (to avoid writing out in detail).
- In the flows we would use the complete terms, however it should be realised that Common terms and ISO 20022 definitions may change between flows, for example for Direct Debit the ISO20022 term is Beneficiary, whilst for Credit Transfer it is Creditor.
- We will endeavour to have the W3C Terms added to the ISO repository as reserved words or ideally as specific mappings, e.g. a Payee is the superclass of both the subclasses of Creditors and Beneficiary.

**Comment by msporny** [comment]
Sounds good. One extra bullet point to add to the proposal that makes it clear how these proposals get implemented in the specifications:
- The W3C Web Payments Terms and their respective mappings to common terms and ISO20022 will be implemented in the Web Payments IG Glossary, which will be dynamically pulled into all WPWG specifications.

**Comment by dlongley** [comment]
+1 to this proposal now

**Comment by bifurcation** [comment]
This looks fine to me.  It's not totally clear to me how this will map to roles in a Web API interaction, but I suppose that will become clearer as the API solidifies.

**Comment by adrianhopebailie** [comment]
@msporny - edited to include your additonal bullet
@bifurcation - have you had a look at the high-level architecture?
https://github.com/w3c/webpayments/wiki/A-Payments-Initiation-Architecture-for-the-Web

**Comment by adrianhopebailie** [comment]
This proposal was RESOLVED during the 28 January meeting with the following addition as proposed by @msporny:
- The W3C Web Payments Terms and their respective mappings to common terms and ISO20022 will be implemented in the Web Payments IG Glossary

The group also noted that all WG specs SHOULD reference the IG glossary but elected to not include this as an explicit dependency in the proposal.

The final resolution was:

The WG will adopt the following terms for use in its deliverables:

| W3C Web Payments Term | Common Terms | ISO 20022 definition |
| --- | --- | --- |
| Payee | Merchant | Creditor, Beneficiary |
| Payee PSP | Acquirer, Gateway | Acquirer, Intermediary |
| Payer | Shopper, Consumer, User | Debtor, Initiator |
| Payer PSP | Wallet | Intermediary |
- We will use the W3C Payments Terms in the W3C specifications (to avoid writing out in detail).
- In the flows we will use the complete terms, however it should be realised that Common terms and ISO 20022 definitions may change between flows, for example for Direct Debit the ISO20022 term is Beneficiary, whilst for Credit Transfer it is Creditor.
- We will endeavour to have the W3C Terms added to the ISO repository as reserved words or ideally as specific mappings, e.g. a Payee is the superclass of both the subclasses of Creditors and Beneficiary.
- The W3C Web Payments Terms and their respective mappings to common terms and ISO20022 will be implemented in the Web Payments IG Glossary

@mountainhippo took an action to liaise with the IG and ensure the terms are part of their glossary  
https://www.w3.org/Payments/WG/track/actions/12
