### ISSUE TITLE
Multilingual Support for human-readable labels

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments#84]
Hi all,

I am following up on an observation from Manu on the mailing list.

There are places in the specs where we have human-readable descriptions (string). 
For example in paymentRequest I see:

 PaymentItem label: "This is a human-readable description of the item. "
 ShippingOption label: "This is a human-readable description of the item. "

I agree with Manu that it seems useful to support internationalization here. I suggest
we check with our I18N colleagues.

Ian

**Comment by nickjshearer** [comment]
Can someone maybe summarize why the Accept-Language header wouldn't - or would - work? The merchant already knows the user's preferred language so can simple pre-fill the items and shipping options with the appropriate strings, if they offer multi-lingual support.

**Comment by rsolomakhin** [comment]
I agree with @nickjshearer. The merchant has several methods of determining user's language: explicit preferences, Accept-Language, geolocation, etc. Some websites utilize user's language to change their display language. The language of the human readable strings passed to the web payments APIs should match the display language of the website.

**Comment by ianbjacobs** [comment]
Thanks Nick and Rouslan for the suggestions.

**Comment by msporny** [comment]
Migrated to https://github.com/w3c/browser-payment-api/issues/53.
