### ISSUE TITLE
Synonym Mapping from Web Environment Terminology to ISO 20022 Terminonogy

### ISSUE THREAD

**Issue by dprophet** [w3c/webpayments#95]
We need a table/mapping of synonyms that are more Web Environment friendly to ISO 20022 terminology.

These issue keeps coming up

https://github.com/w3c/webpayments/issues/59
https://github.com/w3c/webpayments/issues/62
https://github.com/w3c/webpayments/issues/93

**Comment by dprophet** [comment]
Experts in this area point out:
- ISO20022 explicitly states in the Standard that it is bound to the context of "Financial Services". The prior version of ISO 20022 had a "God's eye view", which was a problem.

Look at the below article about "Domain-Driven Design" and BoundedContext

http://martinfowler.com/bliki/BoundedContext.html

The combination of context + name is necessary to solve this problem of ISO 20022 terminology in a Web Domain.

**Comment by fredMeignien** [comment]
Very interesting paper.
ISO20022 applies to a certain context, and my feeling is that we are in WebPayments context...So names should remained bounded to their context until they can take some kind of general meaning...
Fred

**Comment by mattsaxon** [comment]
Erik,  #59 and #62 are closed, creating this resource https://github.com/w3c/webpayments/wiki/ISO-20022-definitions-mapping-on-flows , is there a need for another issue beyond the one I raised in #93 to cover this? The resolution to #93 should update this wiki page IMO.

With regard to Bounded Contexts, it would seem simpler to try to keep this in a Payment Context and try to have a Ubiquitous Language within that. Synonyms can assist with this and that is what the groups has been working towards. I think by having to BCs we create a whole set of mapping issues (in Domain Driven Design this is managed by an Anti-Corruption layer (ACL) which deal with the mappings).

**Comment by dprophet** [comment]
@fredMeignien, correct. Lets assume that Financial Services Context is ISO 20022.

We can use naming within a WebPayments Context and show mapping to the ISO 20022 Context. Ultimately ISO 20022 BC and WebPayments BC can be dynamically mapped as the information enters/leaves one domain.

@mattsaxon Lets try and solve common problems with common solutions. The issue of context is a known problem with ISO 20022. The ISO 20022 Work Group leader (and liaison to W3C) is pointed me in the direction of BC's.

Anti-Corruption layer : Pragmatics vs Semantics. Age old argument. Static structure underlying dynamic behavior. On your list

https://github.com/w3c/webpayments/wiki/ISO-20022-definitions-mapping-on-flows

I argue each of those payment instruments will have different dynamic behaviors on the same underlying static data structures. I actually agree, simpler is easier, but with proper BoundContext's definitions we can automate the transformation between the WebPayments BC and the ISO 20022 BC as required by the the domain specific payment instrument.

Simpler for whom? Ourselves or the 30 years of legacy technologies/standards that need to adapt for the usage over the web?

I dont believe we need to go off the deep end of theory but there are practical solutions to these problems.

Proper BC's and pragmatics will allow us to model the flows of information and its mappings for everyone's needs.

**Comment by mattsaxon** [comment]
I argue it will be simpler for the payment industry as a whole including the web developers and merchants. I haven't seen specific example where the proposed BCs conflict in any meaningful way as yet which don't have simple solutions based on synonyms rather than a full isolation using BCs

Whilst I'm not DDD expert, I'd argue that the BCs are 'Web Development' and 'Payments', WebPayments is not a BC, but an intersection of these.

**Comment by dprophet** [comment]
Matt, I wanted to follow up about ISO 20022, synonyms, and BoundedContext's

**Comment by mattsaxon** [comment]
Sure Erik, what are your thoughts?

You could always come to the Flows Task Force meeting this Friday at 3 to discuss too. Vincent, Kris, Laurent and Cyril are the regular participants so it may be a good forum

**Comment by adrianhopebailie** [comment]
Flows work has moved to it's own repo: https://github.com/w3c/webpayments-flows

**Comment by mattsaxon** [comment]
@adrianhopebailie this is not flows work, it pertains the the API specs using different terminology

**Comment by ianbjacobs** [comment]
Closing this as, in practice, terminology harmonization happens in payment method specs.

**Comment by webpayments** [comment]
Je suis absent(e) du bureau jusqu'au 02/05/2018

Please kindly note my absence for the period mentioned above. You can reach
Béatrice Cocozza at +33 1 40 15 58 50


Remarque : ceci est une réponse automatique à votre message  "Re:
[w3c/webpayments] Synonym Mapping from Web Environment  Terminology to ISO
20022 Terminonogy (#95)" envoyé le 25/04/2018 15:30:26.

C'est la seule notification que vous recevrez pendant l'absence de cette
personne.

--------------------------------------------------------------------------------------------------------------------------------------------
Ce message et toutes les pièces jointes sont confidentiels et établis à l'intention exclusive de ses destinataires. Toute utilisation ou diffusion non autorisée est interdite. Tout message électronique est  susceptible d'altération. Le Groupement des Cartes Bancaires "CB" décline toute responsabilité au titre de ce message s'il a été altéré, déformé ou falsifié.


This message and any attachments are confidential and intended solely for the addressees. Any unauthorised use or dissemination is prohibited. E-mails are susceptible to alteration. Groupement des Cartes bancaires "CB" shall not be liable for the message if altered, changed or falsified.
